name: Run Verilog Testbenches

on:
  push:
    branches:
      - "dev/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog

      - name: Run ProgressReport2
        run: make ci
        working-directory: progress_report_3
